name: Deploy to AWS S3
description: Deploy sttaic website via S3
inputs:
  bucket:
    required: true
    description: 'Bucket name'
  bucket-region:
    required: false
    description: 'Bucket Region'
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website'
runs:
  using: 'node16'
  main: main.js